[pytest]
addopts = --tb=short
DJANGO_SETTINGS_MODULE = tests.settings

[tox]
envlist =
    py{310,311,312,313,314}-dj52-drf318-pytest
    py{312,313,314}-dj60-drf318-pytest
    py{312,313,314}-dj61-drf318-pytest
    py314-dj61-drf318-mypy
skip_missing_interpreters = true

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
django =
    5.2: dj52
    6.0: dj60
    6.1: dj61

[testenv]
setenv =
    PYTHONDONTWRITEBYTECODE=1
    PYTHONWARNINGS=once
deps =
    dj52: Django>=5.2,<6.0
    dj60: Django>=6.0,<6.1
    dj61: Django>=6.1,<6.2
    drf318: djangorestframework>=3.18,<3.19
    pytest: -rrequirements.txt
    mypy: djangorestframework-stubs[compatible-mypy]>=3.18,<3.19
commands=
    pytest: pytest --cov drf_writable_nested --cov-report=xml
    mypy: mypy --show-traceback example
    mypy: mypy --show-traceback .
